### ISSUE TITLE
Programmation de la section header avec HTML & Css

### ISSUE THREAD

**Issue by mednajjar** [mednajjar/Workflow-agenceWeb#1]
veuillez coder votre partie header définie dans la structure HTML et CSS en respectant le mockup que nous avons réalisé.

**Comment by mednajjar** [comment]
bonjour Khadija,
veuillez faire un pull pour actualiser le fichier CSS, j'ai ajouter l'unité pixel au Media Query car j'ai oublier à mettre la dernière fois.
merci.

**Comment by KhadijaZahir** [comment]
ok;thanks

**Comment by KhadijaZahir** [comment]
issue of the header is finished
