### ISSUE TITLE
Programmation de la section footer avec HTML & Css

### ISSUE THREAD

**Issue by mednajjar** [mednajjar/Workflow-agenceWeb#6]
veuillez coder votre partie footer définie dans la structure HTML et CSS en respectant le mockup que nous avons réalisé.

**Comment by mednajjar** [comment]
bonjour sana,
veuillez faire un pull pour actualiser le fichier CSS, j'ai ajouter l'unité pixel au Media Query car j'ai oublier à mettre la dernière fois.
merci.

**Comment by sana-ben036** [comment]
la partie footer est bien finie
